
import React, { useState } from 'react';

const FAQ_DATA = [
  { q: "What is AlgoVisual?", a: "AlgoVisual is a minimalist, high-performance platform for visualizing over 65 data structures and algorithms, featuring integrated AI technical analysis." },
  { q: "How do I start a visualization?", a: "Simply select an algorithm from the sidebar on the left, then click the 'Visualize' button in the main viewport to see the step-by-step animation." },
  { q: "Can I use my own data?", a: "Yes! Click the keyboard icon next to the 'Visualize' button to input custom numbers (up to 20 items) for supported algorithms." },
  { q: "How does the AI Tutor work?", a: "By clicking the 'Deep Analysis' tab, you can request a real-time technical breakdown of the algorithm's performance and use the chat to ask specific questions." },
  { q: "Is AlgoVisual mobile-friendly?", a: "Absolutely. The platform is designed with a responsive layout, ensuring a smooth experience on smartphones, tablets, and desktops." },
  { q: "What algorithms are supported?", a: "We support Sorting, Searching, Graphs, Strings, Advanced DP, Mathematics, Geometry, and much more—totaling over 65 entries." },
  { q: "Is it completely free?", a: "Yes, AlgoVisual is a free educational tool designed to help students and engineers master complex computer science concepts." },
  { q: "What is Big O notation?", a: "It is a mathematical notation used to describe the limiting behavior of a function when the argument tends towards a particular value or infinity—crucial for algorithm efficiency." },
  { q: "Why use visualizations to learn?", a: "Abstract code can be hard to internalize. Seeing variables move and structures evolve in real-time builds strong mental models for complex logic." },
  { q: "How can I change the animation speed?", a: "Use the 'Speed' slider below the visualization window to adjust the delay between animation frames from 50ms to 2000ms." },
  { q: "What do the different colors represent?", a: "Usually, Blue indicates active/selected items, Orange is for comparison, Green shows sorted/visited states, and Red marks targets or errors." },
  { q: "Does it support Dark Mode?", a: "Currently, we focus on a clean, light 'Pristine White' aesthetic to maximize focus and clarity, though accessibility is always a priority." },
  { q: "Can I share my custom data?", a: "The 'Share' button copies a link to the current platform state, allowing others to quickly jump into the same algorithm context." },
  { q: "What technology stack is used?", a: "The app is built using React for UI components, D3.js for high-performance SVG visualizations, and the Gemini API for intelligence." },
  { q: "Is the AI analysis accurate?", a: "The AI analysis is generated by the latest Gemini 3 models, providing expert-level insights, though users should always verify with standard textbooks." }
];

export const HomePage: React.FC<{ onGetStarted: () => void }> = ({ onGetStarted }) => {
  const [showAllFaq, setShowAllFaq] = useState(false);

  return (
    <div className="animate-message pb-20">
      {/* Hero Section */}
      <section className="relative overflow-hidden rounded-[3rem] bg-white border border-slate-100 shadow-xl mb-12">
        <div className="p-8 sm:p-20 text-center flex flex-col items-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-blue-50 text-blue-600 rounded-full text-[10px] font-black uppercase tracking-widest mb-6 w-fit">
            <i className="fa-solid fa-sparkles"></i> AI Powered Visualizer
          </div>
          <h1 className="text-4xl sm:text-7xl font-black text-slate-900 tracking-tight leading-[1.1] mb-6 max-w-3xl mx-auto">
            Master Data Structures <span className="text-blue-600 italic">& Algorithms.</span>
          </h1>
          <p className="text-slate-500 text-base sm:text-xl mb-10 leading-relaxed font-medium max-w-2xl mx-auto">
            Experience logic in motion. Visualize complex code through high-fidelity animations and get real-time technical analysis from our integrated AI engine.
          </p>
          <div className="flex flex-wrap gap-4 justify-center">
            <button 
              onClick={onGetStarted}
              className="px-12 py-5 bg-blue-600 text-white rounded-full text-[11px] font-black uppercase tracking-widest shadow-2xl shadow-blue-100 hover:bg-blue-700 transition-all hover:scale-105"
            >
              Explore Algorithms
            </button>
            <button 
              onClick={() => {
                const faqSection = document.getElementById('faq-section');
                faqSection?.scrollIntoView({ behavior: 'smooth' });
              }}
              className="px-12 py-5 bg-white border-2 border-slate-100 text-slate-600 rounded-full text-[11px] font-black uppercase tracking-widest hover:bg-slate-50 transition-all"
            >
              Learn More
            </button>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-20">
        {[
          { icon: 'fa-diagram-project', title: '65+ Algorithms', desc: 'From basic sorting to advanced graph theory and geometry.' },
          { icon: 'fa-brain', title: 'AI Technical Tutor', desc: 'Real-time complexity analysis and step-by-step guidance.' },
          { icon: 'fa-gauge-high', title: 'Real-time Interaction', desc: 'Adjust speeds, input custom data, and step through logic.' }
        ].map((f, i) => (
          <div key={i} className="p-8 bg-white border border-slate-100 rounded-[2.5rem] shadow-sm hover:shadow-md transition-shadow">
            <div className="w-14 h-14 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center text-xl mb-6 shadow-sm">
              <i className={`fa-solid ${f.icon}`}></i>
            </div>
            <h3 className="text-lg font-black text-slate-900 mb-2">{f.title}</h3>
            <p className="text-slate-500 text-sm leading-relaxed font-medium">{f.desc}</p>
          </div>
        ))}
      </section>

      {/* Showcase Section */}
      <section className="bg-slate-900 rounded-[3rem] p-10 sm:p-20 text-center text-white mb-20 overflow-hidden relative">
        <div className="relative z-10">
          <h2 className="text-3xl sm:text-5xl font-black mb-8 tracking-tight">Visual Learning is <span className="text-blue-400">Superior.</span></h2>
          <p className="text-slate-400 max-w-2xl mx-auto mb-12 text-lg">Stop memorizing patterns. Start understanding flows. Our engine handles the complexity so you can focus on the logic.</p>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 sm:gap-8">
            <div className="p-6 bg-white/5 backdrop-blur-md rounded-3xl border border-white/10">
              <div className="text-3xl font-black mb-1">65+</div>
              <div className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Algos</div>
            </div>
            <div className="p-6 bg-white/5 backdrop-blur-md rounded-3xl border border-white/10">
              <div className="text-3xl font-black mb-1">10+</div>
              <div className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Categories</div>
            </div>
            <div className="p-6 bg-white/5 backdrop-blur-md rounded-3xl border border-white/10">
              <div className="text-3xl font-black mb-1">∞</div>
              <div className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Possibilities</div>
            </div>
            <div className="p-6 bg-white/5 backdrop-blur-md rounded-3xl border border-white/10">
              <div className="text-3xl font-black mb-1">24/7</div>
              <div className="text-[10px] font-black uppercase text-slate-400 tracking-widest">AI Support</div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq-section" className="bg-white rounded-[3rem] border border-slate-100 p-8 sm:p-16 shadow-sm">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-black text-slate-900 tracking-tight mb-4 italic">Frequently Asked Questions</h2>
          <p className="text-slate-500 font-medium">Everything you need to know about the platform.</p>
        </div>
        <div className="space-y-4 max-w-3xl mx-auto">
          {(showAllFaq ? FAQ_DATA : FAQ_DATA.slice(0, 5)).map((item, i) => (
            <div key={i} className="p-6 bg-slate-50/50 rounded-[2rem] border border-slate-50 animate-message" style={{ animationDelay: `${i * 0.05}s` }}>
              <h4 className="font-black text-slate-900 mb-3 flex items-start gap-3">
                <span className="text-blue-600">Q.</span> {item.q}
              </h4>
              <p className="text-sm text-slate-500 font-medium leading-relaxed pl-7">
                {item.a}
              </p>
            </div>
          ))}
        </div>
        {!showAllFaq && (
          <div className="mt-10 text-center">
            <button 
              onClick={() => setShowAllFaq(true)}
              className="px-8 py-4 bg-white border-2 border-slate-100 text-slate-500 rounded-full text-[10px] font-black uppercase tracking-widest hover:bg-slate-50 transition-all"
            >
              Show More Questions ({FAQ_DATA.length - 5} more)
            </button>
          </div>
        )}
      </section>
    </div>
  );
};
